/**
 * Catálogo do acervo. Cada item é um entregável sugerido — ainda não produzido.
 * Para publicar um material real, preencha "fileUrl" com o link final (Drive/PDF).
 * Enquanto "fileUrl" estiver vazio, o formulário mostra "em breve" após o cadastro.
 *
 * "type" controla o formato da prévia interativa no modal (não é o rótulo exibido):
 *   framework  -> prévia em etapas (framework, playbook, fluxograma, one-pager de processo)
 *   ferramenta -> prévia de inputs/resultado (calculadora, planilha, diagnóstico)
 *   analise    -> prévia de achados (análise, compilado de estudos/pesquisas)
 * "typeLabel" é o rótulo específico mostrado no card.
 * "challenges" marca o(s) desafio(s) de negócio que o material resolve, usado no
 * segundo filtro (por desafio) da seção de materiais.
 */
const DELIVERABLES = [
  // ============ FINANÇAS (desafio: aumentar margem) ============
  {
    id: "unit-economics",
    category: "financas",
    categoryLabel: "Finanças",
    type: "framework",
    typeLabel: "Framework",
    title: "Unit Economics para o seu Negócio",
    teaser: "Modelo para calcular CAC, LTV e payback por produto, serviço ou oferta.",
    description:
      "Um framework passo a passo para estruturar o unit economics do seu negócio: como definir CAC por canal, LTV por jornada de cliente e o payback real de cada oferta. Pensado para especialistas, empresas de produto e times comerciais de qualquer segmento.",
    challenges: ["aumentar-margem"],
    fileUrl: "",
  },
  {
    id: "calculadora-ponto-equilibrio",
    category: "financas",
    categoryLabel: "Finanças",
    type: "ferramenta",
    typeLabel: "Calculadora",
    title: "Calculadora de Ponto de Equilíbrio por Oferta",
    teaser: "Descubra quantas vendas cobrem o custo de cada oferta.",
    description:
      "Planilha interativa para simular o ponto de equilíbrio de uma oferta, produto ou serviço: custo fixo, custo variável por cliente, ticket médio e margem. Ajuste os números e veja o cenário mudar em tempo real.",
    challenges: ["aumentar-margem"],
    fileUrl: "",
  },
  {
    id: "indicadores-financeiros-essenciais",
    category: "financas",
    categoryLabel: "Finanças",
    type: "analise",
    typeLabel: "One-pager",
    title: "Indicadores Financeiros que Todo Negócio Deveria Acompanhar",
    teaser: "Uma referência rápida com os números que mostram a saúde financeira do seu negócio.",
    description:
      "Um one-pager com os indicadores financeiros essenciais para acompanhar toda semana: margem, ticket médio, CAC, LTV e fluxo de caixa, organizados em uma única página de consulta rápida.",
    challenges: ["aumentar-margem"],
    fileUrl: "materiais/indicadores-financeiros.pdf",
  },
  {
    id: "calculadora-cac-canal",
    category: "financas",
    categoryLabel: "Finanças",
    type: "ferramenta",
    typeLabel: "Calculadora",
    title: "Calculadora de CAC por Canal de Aquisição",
    teaser: "Descubra qual canal traz clientes mais baratos e qual está pesando no caixa.",
    description:
      "Planilha para calcular o custo de aquisição de clientes por canal (mídia paga, orgânico, indicação, parcerias) e comparar a eficiência de cada um lado a lado.",
    challenges: ["aumentar-margem"],
    fileUrl: "",
  },
  {
    id: "fluxo-aprovacao-investimento-midia",
    category: "financas",
    categoryLabel: "Finanças",
    type: "framework",
    typeLabel: "Fluxograma",
    title: "Fluxo de Aprovação de Investimento em Mídia",
    teaser: "Um passo a passo claro para quem precisa aprovar orçamento de mídia sem travar a operação.",
    description:
      "Fluxograma que organiza as etapas de solicitação, análise e aprovação de investimento em mídia, definindo quem decide em cada faixa de valor.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "playbook-precificacao",
    category: "financas",
    categoryLabel: "Finanças",
    type: "framework",
    typeLabel: "Playbook",
    title: "Playbook de Precificação de Produtos e Serviços",
    teaser: "Como definir preço sem chutar e sem só copiar o concorrente.",
    description:
      "Um playbook com os critérios para precificar produtos e serviços considerando custo, valor percebido e posicionamento, evitando a armadilha de precificar olhando só para o concorrente.",
    challenges: ["aumentar-margem"],
    fileUrl: "",
  },
  {
    id: "estudos-inadimplencia",
    category: "financas",
    categoryLabel: "Finanças",
    type: "analise",
    typeLabel: "Compilado de estudos",
    title: "O que os Estudos Dizem sobre Inadimplência",
    teaser: "Um resumo de estudos públicos sobre por que clientes atrasam pagamento e o que reduz esse risco.",
    description:
      "Uma curadoria de estudos e dados públicos sobre inadimplência: os principais fatores de risco identificados e as práticas que mais reduzem atraso e cancelamento por falta de pagamento.",
    challenges: ["aumentar-margem"],
    fileUrl: "",
  },
  {
    id: "analise-ticket-medio",
    category: "financas",
    categoryLabel: "Finanças",
    type: "analise",
    typeLabel: "Análise de artigos",
    title: "O que Artigos Recentes Dizem sobre Ticket Médio",
    teaser: "Uma leitura organizada sobre elevar o ticket médio sem perder cliente.",
    description:
      "Uma análise de artigos recentes sobre estratégias de aumento de ticket médio: upsell, bundles e reposicionamento de oferta, com os pontos em que os autores mais concordam e discordam.",
    challenges: ["aumentar-margem"],
    fileUrl: "",
  },
  {
    id: "como-calcular-ltv",
    category: "financas",
    categoryLabel: "Finanças",
    type: "analise",
    typeLabel: "One-pager",
    title: "Como Calcular o LTV de um Cliente",
    teaser: "O passo a passo direto para chegar num número de LTV confiável.",
    description:
      "Um one-pager que explica como calcular o LTV (valor do tempo de vida do cliente) com uma fórmula simples e os erros mais comuns que inflam esse número artificialmente.",
    challenges: ["aumentar-margem"],
    fileUrl: "",
  },
  {
    id: "calculadora-desconto-maximo",
    category: "financas",
    categoryLabel: "Finanças",
    type: "ferramenta",
    typeLabel: "Calculadora",
    title: "Calculadora de Desconto Máximo sem Perder Margem",
    teaser: "Descubra até onde dá para descontar antes de a venda deixar de valer a pena.",
    description:
      "Calculadora que cruza custo, margem desejada e ticket para mostrar o desconto máximo que ainda mantém a operação saudável, evitando descontos dados no impulso da negociação.",
    challenges: ["aumentar-margem"],
    fileUrl: "",
  },
  {
    id: "orcamento-anual-comercial",
    category: "financas",
    categoryLabel: "Finanças",
    type: "framework",
    typeLabel: "Framework",
    title: "Orçamento Anual para Áreas Comerciais",
    teaser: "Uma estrutura para planejar o orçamento do ano sem inflar nem subestimar investimento.",
    description:
      "Framework para montar o orçamento anual de marketing e vendas, distribuindo investimento por canal e por trimestre com base em metas de receita.",
    challenges: ["aumentar-margem"],
    fileUrl: "",
  },
  {
    id: "playbook-renegociacao-inadimplencia",
    category: "financas",
    categoryLabel: "Finanças",
    type: "framework",
    typeLabel: "Playbook",
    title: "Playbook de Renegociação de Inadimplência",
    teaser: "Um roteiro para recuperar clientes inadimplentes sem quebrar o relacionamento.",
    description:
      "Playbook com abordagens de renegociação por perfil de cliente inadimplente, da primeira cobrança à proposta de acordo, mantendo a porta aberta para reativação futura.",
    challenges: ["aumentar-margem"],
    fileUrl: "",
  },
  {
    id: "fluxo-fechamento-financeiro",
    category: "financas",
    categoryLabel: "Finanças",
    type: "framework",
    typeLabel: "Fluxograma",
    title: "Fluxo de Fechamento Financeiro Mensal",
    teaser: "O passo a passo para fechar o mês sem correria de última hora.",
    description:
      "Fluxograma com as etapas do fechamento financeiro mensal, da conciliação bancária ao relatório final, com prazos sugeridos para cada etapa.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "metricas-receita-recorrente",
    category: "financas",
    categoryLabel: "Finanças",
    type: "analise",
    typeLabel: "One-pager",
    title: "Métricas de Receita Recorrente para Assinaturas",
    teaser: "As métricas certas para quem vive de receita recorrente e assinatura.",
    description:
      "Um one-pager com as métricas essenciais de receita recorrente: MRR, churn, expansão e net revenue retention, explicadas em linguagem direta.",
    challenges: ["aumentar-margem"],
    fileUrl: "",
  },
  {
    id: "pesquisas-elasticidade-preco",
    category: "financas",
    categoryLabel: "Finanças",
    type: "analise",
    typeLabel: "Compilado de pesquisas",
    title: "O que as Pesquisas Dizem sobre Elasticidade de Preço",
    teaser: "Uma síntese de pesquisas públicas sobre como o preço afeta a decisão de compra.",
    description:
      "Uma curadoria de pesquisas sobre elasticidade de preço: até que ponto um aumento de preço reduz demanda, e em que situações o mercado tolera preços mais altos.",
    challenges: ["aumentar-margem"],
    fileUrl: "",
  },
  {
    id: "calculadora-payback-campanhas",
    category: "financas",
    categoryLabel: "Finanças",
    type: "ferramenta",
    typeLabel: "Calculadora",
    title: "Calculadora de Payback de Campanhas de Aquisição",
    teaser: "Descubra em quantos meses uma campanha de aquisição se paga.",
    description:
      "Calculadora que projeta o payback de uma campanha de aquisição com base em CAC, ticket médio e margem, mostrando em quantos meses o investimento retorna.",
    challenges: ["aumentar-margem", "gerar-demanda"],
    fileUrl: "",
  },

  // ============ MARKETING ============
  {
    id: "panorama-aquisicao",
    category: "marketing",
    categoryLabel: "Marketing",
    type: "analise",
    typeLabel: "Análise",
    title: "Panorama de Aquisição de Clientes",
    teaser: "O que estudos recentes mostram sobre canais, ofertas e custo de aquisição.",
    description:
      "Uma leitura organizada de estudos e dados públicos sobre aquisição de clientes: quais canais têm ganhado espaço, como as ofertas de entrada mudaram e onde o custo de aquisição está subindo mais rápido.",
    challenges: ["gerar-demanda"],
    fileUrl: "",
  },
  {
    id: "funil-vendas-sem-fricao",
    category: "marketing",
    categoryLabel: "Marketing",
    type: "framework",
    typeLabel: "Framework",
    title: "Funil de Vendas sem Fricção",
    teaser: "O desenho de funil que reduz etapas entre o primeiro clique e a venda confirmada.",
    description:
      "Um framework para mapear e redesenhar o funil de vendas: onde cortar etapas, onde automatizar e onde manter contato humano. Inclui checklist de fricções comuns em negócios de qualquer porte.",
    challenges: ["aumentar-conversao"],
    fileUrl: "",
  },
  {
    id: "checklist-pagina-captacao",
    category: "marketing",
    categoryLabel: "Marketing",
    type: "framework",
    typeLabel: "One-pager",
    title: "Checklist de Página de Captação de Alta Conversão",
    teaser: "Os elementos que toda página de captação de alta conversão tem em comum.",
    description:
      "Um checklist com os elementos essenciais de uma página de captação: promessa clara, prova social, formulário curto e CTA visível, prontos para conferir na sua página atual.",
    challenges: ["aumentar-conversao"],
    fileUrl: "",
  },
  {
    id: "calculadora-custo-lead-canal",
    category: "marketing",
    categoryLabel: "Marketing",
    type: "ferramenta",
    typeLabel: "Calculadora",
    title: "Calculadora de Custo por Lead por Canal",
    teaser: "Compare o custo por lead de cada canal lado a lado.",
    description:
      "Planilha para calcular e comparar o custo por lead de cada canal de aquisição, ajudando a decidir onde realocar orçamento de mídia.",
    challenges: ["gerar-demanda"],
    fileUrl: "",
  },
  {
    id: "playbook-campanhas-lancamento",
    category: "marketing",
    categoryLabel: "Marketing",
    type: "framework",
    typeLabel: "Playbook",
    title: "Playbook de Campanhas de Lançamento",
    teaser: "A estrutura de uma campanha de lançamento, do aquecimento ao fechamento.",
    description:
      "Playbook com as fases de uma campanha de lançamento: aquecimento, abertura, urgência e fechamento, com o objetivo de cada etapa.",
    challenges: ["gerar-demanda"],
    fileUrl: "",
  },
  {
    id: "fluxo-jornada-lead-venda",
    category: "marketing",
    categoryLabel: "Marketing",
    type: "framework",
    typeLabel: "Fluxograma",
    title: "Fluxo da Jornada do Lead até a Venda",
    teaser: "Visualize cada etapa que um lead percorre até virar cliente.",
    description:
      "Fluxograma que mapeia a jornada completa do lead, da primeira interação até a venda, apontando onde cada etapa costuma perder mais gente.",
    challenges: ["aumentar-conversao"],
    fileUrl: "",
  },
  {
    id: "estudos-comportamento-busca",
    category: "marketing",
    categoryLabel: "Marketing",
    type: "analise",
    typeLabel: "Compilado de estudos",
    title: "O que os Estudos Dizem sobre Comportamento de Busca",
    teaser: "Um resumo de estudos sobre como as pessoas pesquisam antes de comprar.",
    description:
      "Uma curadoria de estudos sobre comportamento de busca: quantas fontes um comprador consulta, em que momento decide e o que isso muda para o seu conteúdo.",
    challenges: ["gerar-demanda"],
    fileUrl: "",
  },
  {
    id: "analise-anuncios-atuais",
    category: "marketing",
    categoryLabel: "Marketing",
    type: "analise",
    typeLabel: "Análise de posts",
    title: "O que Está Funcionando em Anúncios Hoje",
    teaser: "Um raio-x de formatos e ganchos de anúncio que estão performando agora.",
    description:
      "Uma análise de posts e criativos de anúncios recentes, destacando os formatos, ganchos e estruturas de copy que mais aparecem entre os que performam bem.",
    challenges: ["gerar-demanda"],
    fileUrl: "",
  },
  {
    id: "estrutura-oferta-irresistivel",
    category: "marketing",
    categoryLabel: "Marketing",
    type: "analise",
    typeLabel: "One-pager",
    title: "Estrutura de uma Oferta Irresistível",
    teaser: "Os componentes que fazem uma oferta parecer óbvia de aceitar.",
    description:
      "Um one-pager com a estrutura de uma oferta irresistível: promessa, mecanismo, prova, urgência e garantia, em uma única página para preencher com sua oferta.",
    challenges: ["otimizar-marca"],
    fileUrl: "",
  },
  {
    id: "segmentacao-publico-persona",
    category: "marketing",
    categoryLabel: "Marketing",
    type: "framework",
    typeLabel: "Framework",
    title: "Segmentação de Público por Persona",
    teaser: "Como dividir seu público em personas que realmente mudam sua comunicação.",
    description:
      "Framework para construir personas a partir de dados reais de cliente, evitando personas genéricas que não mudam nada na prática do marketing.",
    challenges: ["otimizar-marca"],
    fileUrl: "",
  },
  {
    id: "calculadora-orcamento-midia-meta",
    category: "marketing",
    categoryLabel: "Marketing",
    type: "ferramenta",
    typeLabel: "Calculadora",
    title: "Calculadora de Orçamento de Mídia por Meta de Vendas",
    teaser: "Descubra quanto investir em mídia para bater a meta do mês.",
    description:
      "Calculadora que parte da meta de vendas e do funil de conversão para indicar o orçamento de mídia necessário para alcançá-la.",
    challenges: ["gerar-demanda"],
    fileUrl: "",
  },
  {
    id: "playbook-reativacao-leads-frios",
    category: "marketing",
    categoryLabel: "Marketing",
    type: "framework",
    typeLabel: "Playbook",
    title: "Playbook de Reativação de Leads Frios",
    teaser: "Como acordar uma base de leads que parou de responder.",
    description:
      "Playbook com sequências de reativação para leads frios: novo ângulo de oferta, prova social recente e um motivo real para voltar a conversar.",
    challenges: ["gerar-demanda"],
    fileUrl: "",
  },
  {
    id: "fluxo-aprovacao-criativos",
    category: "marketing",
    categoryLabel: "Marketing",
    type: "framework",
    typeLabel: "Fluxograma",
    title: "Fluxo de Aprovação de Criativos e Campanhas",
    teaser: "Um processo para aprovar criativos sem virar gargalo do time.",
    description:
      "Fluxograma com as etapas de aprovação de criativos e campanhas, definindo quem revisa o quê e em quanto tempo, para a campanha não travar esperando aprovação.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "metricas-marketing-importantes",
    category: "marketing",
    categoryLabel: "Marketing",
    type: "analise",
    typeLabel: "One-pager",
    title: "Métricas de Marketing que Realmente Importam",
    teaser: "Menos dashboard, mais números que de fato indicam se o marketing está funcionando.",
    description:
      "Um one-pager com as métricas de marketing mais conectadas a receita, para parar de acompanhar números que não mudam nenhuma decisão.",
    challenges: ["gerar-demanda"],
    fileUrl: "",
  },
  {
    id: "pesquisas-prova-social",
    category: "marketing",
    categoryLabel: "Marketing",
    type: "analise",
    typeLabel: "Compilado de pesquisas",
    title: "O que as Pesquisas Dizem sobre Prova Social",
    teaser: "Uma síntese de pesquisas sobre por que prova social converte.",
    description:
      "Uma curadoria de pesquisas sobre prova social: que tipo de depoimento pesa mais na decisão de compra e em que etapa da jornada ele funciona melhor.",
    challenges: ["aumentar-conversao", "otimizar-marca"],
    fileUrl: "",
  },
  {
    id: "analise-seo-site",
    category: "marketing",
    categoryLabel: "Marketing",
    type: "analise",
    typeLabel: "Análise de artigos",
    title: "Como Está o SEO do seu Site",
    teaser: "Uma leitura guiada de artigos recentes para avaliar o SEO do seu site.",
    description:
      "Uma análise de artigos recentes sobre SEO, organizada como um guia de autoavaliação para checar os pontos mais atuais no seu próprio site.",
    challenges: ["gerar-demanda"],
    fileUrl: "",
  },

  // ============ VENDAS ============
  {
    id: "diagnostico-maturidade-comercial",
    category: "vendas",
    categoryLabel: "Vendas",
    type: "ferramenta",
    typeLabel: "Diagnóstico",
    title: "Diagnóstico de Maturidade Comercial",
    teaser: "Um raio-x rápido do seu time comercial, com plano de próximos passos.",
    description:
      "Questionário guiado que avalia processo comercial, uso de dados, previsibilidade de receita e estrutura de time. Ao final, você recebe um raio-x com prioridades para organizar a operação comercial.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "playbook-objecoes",
    category: "vendas",
    categoryLabel: "Vendas",
    type: "framework",
    typeLabel: "Playbook",
    title: "Playbook de Objeções de Vendas",
    teaser: "Estrutura de resposta para as objeções mais comuns na venda consultiva.",
    description:
      "Um playbook com estrutura de resposta para objeções recorrentes na venda de produtos e serviços de ticket alto: preço, tempo, concorrência e dúvida sobre resultado. Adaptável a qualquer segmento.",
    challenges: ["aumentar-conversao"],
    fileUrl: "",
  },
  {
    id: "script-qualificacao-leads",
    category: "vendas",
    categoryLabel: "Vendas",
    type: "framework",
    typeLabel: "One-pager",
    title: "Script de Qualificação de Leads",
    teaser: "As perguntas certas para separar quem está pronto para comprar de quem só está curioso.",
    description:
      "Um one-pager com um script de qualificação direto, com as perguntas que revelam orçamento, urgência e autoridade de decisão do lead.",
    challenges: ["aumentar-conversao"],
    fileUrl: "",
  },
  {
    id: "calculadora-meta-vendas-vendedor",
    category: "vendas",
    categoryLabel: "Vendas",
    type: "ferramenta",
    typeLabel: "Calculadora",
    title: "Calculadora de Meta de Vendas por Vendedor",
    teaser: "Distribua a meta do time de forma justa e realista.",
    description:
      "Calculadora que distribui a meta comercial do time entre vendedores considerando histórico individual e capacidade de atendimento.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "fluxo-comercial-primeiro-contato-venda",
    category: "vendas",
    categoryLabel: "Vendas",
    type: "framework",
    typeLabel: "Fluxograma",
    title: "Fluxo Comercial do Primeiro Contato à Venda",
    teaser: "Visualize o processo comercial completo em uma única imagem.",
    description:
      "Fluxograma do processo comercial completo, do primeiro contato à assinatura, com os pontos de decisão e critérios de avanço entre etapas.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "estudos-tempo-resposta-conversao",
    category: "vendas",
    categoryLabel: "Vendas",
    type: "analise",
    typeLabel: "Compilado de estudos",
    title: "O que os Estudos Dizem sobre Tempo de Resposta e Conversão",
    teaser: "Um resumo de estudos sobre o quanto a velocidade de resposta afeta a venda.",
    description:
      "Uma curadoria de estudos sobre tempo de resposta comercial e sua relação com taxa de conversão, com os intervalos de tempo mais citados como ponto de virada.",
    challenges: ["aumentar-conversao"],
    fileUrl: "",
  },
  {
    id: "analise-vendas-consultivas",
    category: "vendas",
    categoryLabel: "Vendas",
    type: "analise",
    typeLabel: "Análise de artigos",
    title: "O que Artigos Dizem sobre Vendas Consultivas",
    teaser: "Uma leitura organizada sobre o que diferencia uma venda consultiva de uma venda comum.",
    description:
      "Uma análise de artigos sobre venda consultiva, reunindo os pontos em que diferentes autores concordam sobre o papel da escuta e do diagnóstico antes da proposta.",
    challenges: ["aumentar-conversao"],
    fileUrl: "",
  },
  {
    id: "checklist-onboarding-vendedores",
    category: "vendas",
    categoryLabel: "Vendas",
    type: "framework",
    typeLabel: "One-pager",
    title: "Checklist de Onboarding de Vendedores",
    teaser: "O que um vendedor novo precisa saber antes da primeira ligação.",
    description:
      "Checklist de onboarding comercial com o conteúdo mínimo que um vendedor novo precisa dominar antes de falar com o primeiro lead.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "playbook-follow-up-estruturado",
    category: "vendas",
    categoryLabel: "Vendas",
    type: "framework",
    typeLabel: "Playbook",
    title: "Follow-up Estruturado",
    teaser: "Um roteiro de follow-up para parar de perder venda por falta de contato.",
    description:
      "Playbook de follow-up com cadência sugerida, canal por tentativa e o que dizer em cada contato até a resposta do lead.",
    challenges: ["aumentar-conversao"],
    fileUrl: "",
  },
  {
    id: "cadencia-contato-temperatura-lead",
    category: "vendas",
    categoryLabel: "Vendas",
    type: "framework",
    typeLabel: "Framework",
    title: "Cadência de Contato por Temperatura do Lead",
    teaser: "Trate lead quente e lead frio de formas diferentes, de propósito.",
    description:
      "Framework de cadência de contato que varia frequência e canal conforme a temperatura do lead, evitando tratar todo mundo com o mesmo roteiro.",
    challenges: ["aumentar-conversao"],
    fileUrl: "",
  },
  {
    id: "calculadora-comissionamento-comercial",
    category: "vendas",
    categoryLabel: "Vendas",
    type: "ferramenta",
    typeLabel: "Calculadora",
    title: "Calculadora de Comissionamento Comercial",
    teaser: "Simule diferentes modelos de comissão antes de aplicar no time.",
    description:
      "Calculadora para simular modelos de comissionamento comercial (fixo, escalonado, por margem) e comparar o impacto de cada um na motivação e no custo.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "fluxo-escalonamento-negociacoes-dificeis",
    category: "vendas",
    categoryLabel: "Vendas",
    type: "framework",
    typeLabel: "Fluxograma",
    title: "Fluxo de Escalonamento de Negociações Difíceis",
    teaser: "Saiba exatamente quando uma negociação precisa subir para a liderança.",
    description:
      "Fluxograma que define os critérios para escalar uma negociação difícil para a liderança comercial, evitando que o vendedor decida sozinho em situações de risco.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "perguntas-qualificacao-vendedor",
    category: "vendas",
    categoryLabel: "Vendas",
    type: "analise",
    typeLabel: "One-pager",
    title: "Perguntas de Qualificação que Todo Vendedor Deveria Fazer",
    teaser: "Uma lista pronta de perguntas para nunca mais entrar numa call sem direção.",
    description:
      "Um one-pager com perguntas de qualificação organizadas por objetivo (dor, orçamento, urgência e decisão), prontas para usar em qualquer chamada comercial.",
    challenges: ["aumentar-conversao"],
    fileUrl: "",
  },
  {
    id: "pesquisas-gatilhos-decisao",
    category: "vendas",
    categoryLabel: "Vendas",
    type: "analise",
    typeLabel: "Compilado de pesquisas",
    title: "O que as Pesquisas Dizem sobre Gatilhos de Decisão",
    teaser: "Uma síntese de pesquisas sobre o que realmente move a decisão de compra.",
    description:
      "Uma curadoria de pesquisas sobre gatilhos de decisão de compra: urgência, escassez, autoridade e prova social, com o que cada estudo aponta como mais eficaz.",
    challenges: ["aumentar-conversao"],
    fileUrl: "",
  },
  {
    id: "playbook-recuperacao-vendas-perdidas",
    category: "vendas",
    categoryLabel: "Vendas",
    type: "framework",
    typeLabel: "Playbook",
    title: "Recuperação de Vendas Perdidas",
    teaser: "Um roteiro para reabrir negociações que esfriaram.",
    description:
      "Playbook para retomar contato com oportunidades perdidas, identificando o motivo real da perda antes de tentar reabrir a negociação.",
    challenges: ["aumentar-conversao"],
    fileUrl: "",
  },
  {
    id: "analise-crm-times-comerciais",
    category: "vendas",
    categoryLabel: "Vendas",
    type: "analise",
    typeLabel: "Análise de posts",
    title: "CRM para Times Comerciais em Análise",
    teaser: "Uma leitura do que times comerciais têm comentado sobre uso de CRM.",
    description:
      "Uma análise de posts sobre uso de CRM em times comerciais, reunindo reclamações e elogios recorrentes para ajudar na escolha ou revisão da ferramenta.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },

  // ============ IA ============
  {
    id: "ia-orquestracao-receita",
    category: "ia",
    categoryLabel: "IA",
    type: "analise",
    typeLabel: "Análise",
    title: "IA e Receita: da Automação de Tarefas à Orquestração",
    teaser: "Por que executar ficou fácil e orquestrar virou o novo diferencial competitivo.",
    description:
      "Uma análise sobre como a IA mudou o custo de execução em marketing, vendas e conteúdo, e por que a vantagem competitiva migrou para quem sabe orquestrar essas peças em uma máquina de receita coerente.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "checklist-maturidade-ia-comercial",
    category: "ia",
    categoryLabel: "IA",
    type: "ferramenta",
    typeLabel: "Diagnóstico",
    title: "Checklist de Maturidade de IA para Times Comerciais",
    teaser: "Onde seu time já usa IA de verdade e onde ainda é só promessa.",
    description:
      "Checklist prático para avaliar o uso real de IA em marketing, vendas e atendimento: da captação de leads ao follow-up comercial. Aponta os pontos onde a automação ainda depende de esforço manual.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "onde-ia-assume-tarefas-funil",
    category: "ia",
    categoryLabel: "IA",
    type: "analise",
    typeLabel: "One-pager",
    title: "Onde a IA Já Pode Assumir Tarefas no Funil de Receita",
    teaser: "Um mapa rápido do que já dá para automatizar com IA hoje, sem exagero.",
    description:
      "Um one-pager que mapeia, etapa por etapa do funil de receita, onde a IA já substitui trabalho manual de forma confiável e onde ainda exige supervisão humana.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "adocao-ia-etapa-funil",
    category: "ia",
    categoryLabel: "IA",
    type: "framework",
    typeLabel: "Framework",
    title: "Adoção de IA por Etapa do Funil",
    teaser: "Um roteiro para introduzir IA no funil sem quebrar o que já funciona.",
    description:
      "Framework para priorizar em que etapa do funil começar a usar IA, considerando volume de trabalho manual e risco de erro em cada etapa.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "implantacao-atendimento-ia",
    category: "ia",
    categoryLabel: "IA",
    type: "framework",
    typeLabel: "Playbook",
    title: "Implantação de Atendimento com IA",
    teaser: "Um passo a passo para colocar IA no atendimento sem piorar a experiência do cliente.",
    description:
      "Playbook com as etapas de implantação de atendimento com IA: o que automatizar primeiro, como testar antes de liberar e quando manter atendimento humano.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "automatizar-ou-manter-humano",
    category: "ia",
    categoryLabel: "IA",
    type: "framework",
    typeLabel: "Fluxograma",
    title: "Automatizar ou Manter Humano: Guia de Decisão",
    teaser: "Um fluxo simples para decidir o que vale automatizar e o que não vale.",
    description:
      "Fluxograma de decisão que ajuda a escolher entre automatizar uma tarefa com IA ou manter uma pessoa responsável, considerando risco, volume e complexidade.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "estudos-produtividade-ia-marketing-vendas",
    category: "ia",
    categoryLabel: "IA",
    type: "analise",
    typeLabel: "Compilado de estudos",
    title: "O que os Estudos Dizem sobre Produtividade com IA em Marketing e Vendas",
    teaser: "Um resumo de estudos sobre ganho real de produtividade com IA.",
    description:
      "Uma curadoria de estudos sobre o impacto da IA na produtividade de times de marketing e vendas, com os ganhos mais consistentemente reportados.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "ferramentas-ia-analise",
    category: "ia",
    categoryLabel: "IA",
    type: "analise",
    typeLabel: "Análise de artigos",
    title: "Ferramentas de IA em Análise",
    teaser: "Uma leitura organizada sobre as ferramentas de IA mais comentadas para negócios.",
    description:
      "Uma análise de artigos recentes sobre ferramentas de IA aplicadas a negócios, comparando o que cada uma promete resolver.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "prompts-prontos-comercial",
    category: "ia",
    categoryLabel: "IA",
    type: "framework",
    typeLabel: "One-pager",
    title: "Prompts Prontos para Times Comerciais",
    teaser: "Prompts testados para acelerar tarefas comerciais do dia a dia.",
    description:
      "Um one-pager com prompts prontos para tarefas comerciais recorrentes: resumo de reunião, follow-up e qualificação de lead.",
    challenges: ["aumentar-conversao"],
    fileUrl: "",
  },
  {
    id: "calculadora-economia-tempo-ia",
    category: "ia",
    categoryLabel: "IA",
    type: "ferramenta",
    typeLabel: "Calculadora",
    title: "Calculadora de Economia de Tempo com Automação de IA",
    teaser: "Estime quantas horas por semana a automação com IA pode liberar do time.",
    description:
      "Calculadora que estima a economia de tempo ao automatizar tarefas repetitivas com IA, com base no volume atual de tarefas manuais do time.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "governanca-dados-ia",
    category: "ia",
    categoryLabel: "IA",
    type: "framework",
    typeLabel: "Framework",
    title: "Governança de Dados para Uso de IA",
    teaser: "Regras básicas para usar IA sem colocar dados sensíveis em risco.",
    description:
      "Framework com regras básicas de governança de dados para uso de IA: o que pode e o que não pode ser inserido em ferramentas externas.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "criacao-conteudo-ia-voz-marca",
    category: "ia",
    categoryLabel: "IA",
    type: "framework",
    typeLabel: "Playbook",
    title: "Criação de Conteúdo com IA sem Perder a Voz da Marca",
    teaser: "Como usar IA na produção de conteúdo sem soar genérico.",
    description:
      "Playbook para usar IA na criação de conteúdo mantendo a voz da marca: o que revisar sempre, e os sinais de que um texto soa genérico demais.",
    challenges: ["otimizar-marca"],
    fileUrl: "",
  },
  {
    id: "fluxo-aprovacao-conteudo-ia",
    category: "ia",
    categoryLabel: "IA",
    type: "framework",
    typeLabel: "Fluxograma",
    title: "Fluxo de Aprovação de Conteúdo Gerado por IA",
    teaser: "Um processo de revisão para nada gerado por IA sair sem checagem.",
    description:
      "Fluxograma com as etapas de revisão de conteúdo gerado por IA antes da publicação, incluindo checagem de fatos e alinhamento de tom.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "riscos-ia-comunicacao-clientes",
    category: "ia",
    categoryLabel: "IA",
    type: "analise",
    typeLabel: "One-pager",
    title: "Riscos Comuns do Uso de IA em Comunicação com Clientes",
    teaser: "Os erros mais comuns ao colocar IA para falar direto com o cliente.",
    description:
      "Um one-pager com os riscos mais comuns de usar IA na comunicação direta com clientes, e como reduzir cada um deles.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "pesquisas-adocao-ia-negocios",
    category: "ia",
    categoryLabel: "IA",
    type: "analise",
    typeLabel: "Compilado de pesquisas",
    title: "O que as Pesquisas Dizem sobre Adoção de IA nos Negócios",
    teaser: "Uma síntese de pesquisas sobre como negócios estão realmente adotando IA.",
    description:
      "Uma curadoria de pesquisas sobre adoção de IA em negócios, mostrando a diferença entre o que se fala e o que de fato está em uso.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "tendencias-ia-negocios",
    category: "ia",
    categoryLabel: "IA",
    type: "analise",
    typeLabel: "Análise de posts",
    title: "Tendências de IA Aplicada a Negócios",
    teaser: "Um raio-x do que está sendo mais comentado sobre IA aplicada a negócios.",
    description:
      "Uma análise de posts recentes sobre tendências de IA aplicada a negócios, separando o que é sinal do que é apenas ruído.",
    challenges: ["otimizar-marca"],
    fileUrl: "",
  },

  // ============ PRODUTO ============
  {
    id: "jornada-cliente-produto",
    category: "produto",
    categoryLabel: "Produto",
    type: "framework",
    typeLabel: "Framework",
    title: "Desenho de Jornada do Cliente como Produto",
    teaser: "Trate a jornada do cliente como um produto: com etapas, métricas e dono de cada uma.",
    description:
      "Framework para desenhar a jornada do cliente com a mesma disciplina de um produto digital: etapas claras, métrica de sucesso por etapa e responsável definido. Reduz abandono e aumenta indicação.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "planilha-priorizacao-ofertas",
    category: "produto",
    categoryLabel: "Produto",
    type: "ferramenta",
    typeLabel: "Planilha",
    title: "Planilha de Priorização de Ofertas",
    teaser: "Compare novas ofertas por esforço, potencial de receita e aderência ao público.",
    description:
      "Planilha para pontuar e comparar novas ofertas, produtos ou linhas antes de investir em lançamento: esforço de produção, potencial de receita e aderência ao público atual.",
    challenges: ["otimizar-marca"],
    fileUrl: "",
  },
  {
    id: "anatomia-oferta-bem-estruturada",
    category: "produto",
    categoryLabel: "Produto",
    type: "analise",
    typeLabel: "One-pager",
    title: "Anatomia de uma Oferta Bem Estruturada",
    teaser: "Os componentes de uma oferta que fica clara para o cliente de primeira.",
    description:
      "Um one-pager que desmonta a anatomia de uma oferta bem estruturada: o que ela resolve, para quem, como funciona e por que agora.",
    challenges: ["otimizar-marca"],
    fileUrl: "",
  },
  {
    id: "fluxo-onboarding-novo-cliente",
    category: "produto",
    categoryLabel: "Produto",
    type: "framework",
    typeLabel: "Fluxograma",
    title: "Fluxo de Onboarding de Novo Cliente",
    teaser: "O caminho ideal entre a compra e o primeiro resultado do cliente.",
    description:
      "Fluxograma de onboarding que mapeia as etapas entre a compra e o primeiro resultado percebido pelo cliente, reduzindo abandono no início.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "lancamento-novo-produto-servico",
    category: "produto",
    categoryLabel: "Produto",
    type: "framework",
    typeLabel: "Playbook",
    title: "Lançamento de Novo Produto ou Serviço",
    teaser: "Um roteiro para lançar sem virar um caos de última hora.",
    description:
      "Playbook de lançamento com as etapas de preparação, comunicação interna e externa, e acompanhamento pós-lançamento de um novo produto ou serviço.",
    challenges: ["gerar-demanda"],
    fileUrl: "",
  },
  {
    id: "estudos-churn-cancelamento",
    category: "produto",
    categoryLabel: "Produto",
    type: "analise",
    typeLabel: "Compilado de estudos",
    title: "O que os Estudos Dizem sobre Churn e Cancelamento",
    teaser: "Um resumo de estudos sobre os motivos reais de cancelamento.",
    description:
      "Uma curadoria de estudos sobre churn, reunindo os motivos de cancelamento mais recorrentes apontados em diferentes pesquisas.",
    challenges: ["aumentar-margem"],
    fileUrl: "",
  },
  {
    id: "desenho-experiencia-analise",
    category: "produto",
    categoryLabel: "Produto",
    type: "analise",
    typeLabel: "Análise de artigos",
    title: "Desenho de Experiência em Análise",
    teaser: "Uma leitura organizada sobre o que faz uma experiência de produto ser memorável.",
    description:
      "Uma análise de artigos sobre desenho de experiência, destacando os princípios mais citados por quem escreve sobre o tema.",
    challenges: ["otimizar-marca"],
    fileUrl: "",
  },
  {
    id: "checklist-experiencia-primeira-semana",
    category: "produto",
    categoryLabel: "Produto",
    type: "framework",
    typeLabel: "One-pager",
    title: "Checklist de Experiência do Cliente na Primeira Semana",
    teaser: "O que garantir na primeira semana para o cliente não desistir cedo.",
    description:
      "Checklist com os pontos de contato essenciais da primeira semana do cliente, o momento em que a maior parte do abandono acontece.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "priorizacao-roadmap-produto",
    category: "produto",
    categoryLabel: "Produto",
    type: "framework",
    typeLabel: "Framework",
    title: "Priorização de Roadmap de Produto",
    teaser: "Um critério claro para decidir o que entra no roadmap primeiro.",
    description:
      "Framework de priorização de roadmap que cruza impacto no cliente, esforço de entrega e alinhamento estratégico para ordenar o que construir primeiro.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "calculadora-viabilidade-nova-oferta",
    category: "produto",
    categoryLabel: "Produto",
    type: "ferramenta",
    typeLabel: "Calculadora",
    title: "Calculadora de Viabilidade de Nova Oferta",
    teaser: "Descubra se uma nova oferta se paga antes de investir tempo nela.",
    description:
      "Calculadora que estima a viabilidade de uma nova oferta cruzando custo de desenvolvimento, potencial de receita e tamanho de público estimado.",
    challenges: ["aumentar-margem"],
    fileUrl: "",
  },
  {
    id: "coleta-feedback-clientes",
    category: "produto",
    categoryLabel: "Produto",
    type: "framework",
    typeLabel: "Playbook",
    title: "Coleta de Feedback de Clientes",
    teaser: "Um roteiro para coletar feedback que realmente vira decisão.",
    description:
      "Playbook de coleta de feedback com perguntas certas por momento da jornada, e como organizar as respostas para virarem decisões de produto.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "fluxo-ciclo-vida-cliente",
    category: "produto",
    categoryLabel: "Produto",
    type: "framework",
    typeLabel: "Fluxograma",
    title: "Fluxo do Ciclo de Vida do Cliente",
    teaser: "Visualize todo o ciclo de vida do cliente em uma única imagem.",
    description:
      "Fluxograma do ciclo de vida do cliente, da aquisição à expansão ou ao cancelamento, com o objetivo de cada estágio.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "sinais-oferta-precisa-reformulacao",
    category: "produto",
    categoryLabel: "Produto",
    type: "analise",
    typeLabel: "One-pager",
    title: "Sinais de que uma Oferta Precisa ser Reformulada",
    teaser: "Os sinais de alerta antes de uma oferta parar de vender de vez.",
    description:
      "Um one-pager com os sinais mais comuns de que uma oferta está perdendo relevância e precisa ser revisada antes que as vendas caiam de vez.",
    challenges: ["otimizar-marca"],
    fileUrl: "",
  },
  {
    id: "pesquisas-formatos-consumo",
    category: "produto",
    categoryLabel: "Produto",
    type: "analise",
    typeLabel: "Compilado de pesquisas",
    title: "O que as Pesquisas Dizem sobre Formatos de Consumo",
    teaser: "Uma síntese de pesquisas sobre como as pessoas preferem consumir produtos hoje.",
    description:
      "Uma curadoria de pesquisas sobre formatos de consumo, mostrando como preferências têm mudado e o que isso sugere para o desenho de novas ofertas.",
    challenges: ["otimizar-marca"],
    fileUrl: "",
  },
  {
    id: "segmentacao-portfolio-produtos",
    category: "produto",
    categoryLabel: "Produto",
    type: "framework",
    typeLabel: "Framework",
    title: "Segmentação de Portfólio de Produtos",
    teaser: "Organize seu portfólio para saber o que priorizar de verdade.",
    description:
      "Framework para segmentar o portfólio de produtos por rentabilidade e potencial de crescimento, revelando o que priorizar e o que descontinuar.",
    challenges: ["aumentar-margem"],
    fileUrl: "",
  },
  {
    id: "gamificacao-produtos-analise",
    category: "produto",
    categoryLabel: "Produto",
    type: "analise",
    typeLabel: "Análise de posts",
    title: "Gamificação Aplicada a Produtos em Análise",
    teaser: "Uma leitura do que está sendo comentado sobre gamificação em produtos.",
    description:
      "Uma análise de posts sobre gamificação aplicada a produtos, reunindo exemplos e opiniões recorrentes sobre o que funciona e o que soa forçado.",
    challenges: ["aumentar-conversao"],
    fileUrl: "",
  },

  // ============ TECNOLOGIA ============
  {
    id: "martech-stack",
    category: "tecnologia",
    categoryLabel: "Tecnologia",
    type: "analise",
    typeLabel: "Análise",
    title: "Martech Stack: o que Priorizar em Cada Estágio",
    teaser: "Qual ferramenta faz sentido primeiro, de acordo com o tamanho do negócio.",
    description:
      "Uma análise de como montar a stack de martech em ordem de prioridade, conforme o estágio do negócio: do CRM básico à automação de marketing e BI comercial.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "diagnostico-maturidade-martech",
    category: "tecnologia",
    categoryLabel: "Tecnologia",
    type: "ferramenta",
    typeLabel: "Diagnóstico",
    title: "Diagnóstico de Maturidade Martech",
    teaser: "Avalie se sua stack de ferramentas está pronta para escalar aquisição.",
    description:
      "Diagnóstico guiado para avaliar a maturidade da stack de martech atual: integração entre ferramentas, qualidade de dados e capacidade de automação. Aponta o próximo investimento com maior retorno.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "ferramentas-essenciais-estagio-negocio",
    category: "tecnologia",
    categoryLabel: "Tecnologia",
    type: "analise",
    typeLabel: "One-pager",
    title: "Ferramentas Essenciais por Estágio do Negócio",
    teaser: "Qual ferramenta priorizar primeiro, dependendo do tamanho do negócio.",
    description:
      "Um one-pager que organiza as ferramentas essenciais por estágio do negócio, evitando comprar tecnologia grande demais para o tamanho atual.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "fluxo-integracao-crm-automacao-produto",
    category: "tecnologia",
    categoryLabel: "Tecnologia",
    type: "framework",
    typeLabel: "Fluxograma",
    title: "Fluxo de Integração entre CRM, Automação e Produto",
    teaser: "Visualize como os dados deveriam fluir entre suas principais ferramentas.",
    description:
      "Fluxograma que mapeia como os dados deveriam fluir entre CRM, automação de marketing e a plataforma de produto, evitando informação duplicada ou perdida.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "migracao-ferramentas-sem-perder-dados",
    category: "tecnologia",
    categoryLabel: "Tecnologia",
    type: "framework",
    typeLabel: "Playbook",
    title: "Migração de Ferramentas sem Perder Dados",
    teaser: "Um roteiro para trocar de ferramenta sem perder histórico.",
    description:
      "Playbook de migração de ferramentas com checklist de dados a exportar, período de operação em paralelo e critérios para considerar a migração concluída.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "estudos-roi-martech",
    category: "tecnologia",
    categoryLabel: "Tecnologia",
    type: "analise",
    typeLabel: "Compilado de estudos",
    title: "O que os Estudos Dizem sobre ROI de Martech",
    teaser: "Um resumo de estudos sobre retorno real de investimento em martech.",
    description:
      "Uma curadoria de estudos sobre ROI de martech, reunindo o que diferentes pesquisas apontam como retorno médio de cada tipo de ferramenta.",
    challenges: ["aumentar-margem"],
    fileUrl: "",
  },
  {
    id: "plataformas-ferramentas-analise",
    category: "tecnologia",
    categoryLabel: "Tecnologia",
    type: "analise",
    typeLabel: "Análise de artigos",
    title: "Plataformas e Ferramentas em Análise",
    teaser: "Uma leitura organizada sobre as plataformas mais comparadas do momento.",
    description:
      "Uma análise de artigos recentes comparando plataformas e ferramentas de tecnologia para negócios, reunindo os critérios de comparação mais usados.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "checklist-seguranca-dados-clientes",
    category: "tecnologia",
    categoryLabel: "Tecnologia",
    type: "framework",
    typeLabel: "One-pager",
    title: "Checklist de Segurança de Dados de Clientes",
    teaser: "O mínimo que todo negócio deveria checar sobre segurança de dados.",
    description:
      "Checklist com os pontos mínimos de segurança de dados de clientes que toda operação deveria ter, independente do tamanho do negócio.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "selecao-fornecedores-tecnologia",
    category: "tecnologia",
    categoryLabel: "Tecnologia",
    type: "framework",
    typeLabel: "Framework",
    title: "Seleção de Fornecedores de Tecnologia",
    teaser: "Um critério claro para escolher fornecedor de tecnologia sem se arrepender depois.",
    description:
      "Framework de seleção de fornecedores de tecnologia com critérios de avaliação além do preço: suporte, integrações e histórico de estabilidade.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "calculadora-custo-total-propriedade-stack",
    category: "tecnologia",
    categoryLabel: "Tecnologia",
    type: "ferramenta",
    typeLabel: "Calculadora",
    title: "Calculadora de Custo Total de Propriedade da Stack",
    teaser: "Descubra o custo real da sua stack de tecnologia, além da mensalidade.",
    description:
      "Calculadora que soma o custo total de propriedade de uma stack de tecnologia, incluindo implantação, treinamento e manutenção, não só a mensalidade.",
    challenges: ["aumentar-margem"],
    fileUrl: "",
  },
  {
    id: "implantacao-novo-crm",
    category: "tecnologia",
    categoryLabel: "Tecnologia",
    type: "framework",
    typeLabel: "Playbook",
    title: "Implantação de Novo CRM",
    teaser: "Um roteiro para o time realmente adotar o CRM novo.",
    description:
      "Playbook de implantação de CRM com as etapas de configuração, migração de dados e adoção pelo time, o ponto onde mais implantações falham.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "fluxo-dados-marketing-vendas",
    category: "tecnologia",
    categoryLabel: "Tecnologia",
    type: "framework",
    typeLabel: "Fluxograma",
    title: "Fluxo de Dados entre Marketing e Vendas",
    teaser: "Visualize onde os dados se perdem entre marketing e vendas.",
    description:
      "Fluxograma que mapeia o fluxo de dados entre marketing e vendas, apontando os pontos mais comuns de perda de informação entre as duas áreas.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "sinais-stack-obsoleta",
    category: "tecnologia",
    categoryLabel: "Tecnologia",
    type: "analise",
    typeLabel: "One-pager",
    title: "Sinais de que sua Stack Está Ficando Obsoleta",
    teaser: "Os sinais de que sua stack de tecnologia está atrasando o negócio.",
    description:
      "Um one-pager com os sinais mais comuns de que a stack de tecnologia atual está limitando o crescimento em vez de sustentá-lo.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "pesquisas-automacao-marketing",
    category: "tecnologia",
    categoryLabel: "Tecnologia",
    type: "analise",
    typeLabel: "Compilado de pesquisas",
    title: "O que as Pesquisas Dizem sobre Automação de Marketing",
    teaser: "Uma síntese de pesquisas sobre o real impacto da automação de marketing.",
    description:
      "Uma curadoria de pesquisas sobre automação de marketing, mostrando o que diferentes estudos apontam como maior ganho e maior risco de automatizar demais.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "priorizacao-integracoes",
    category: "tecnologia",
    categoryLabel: "Tecnologia",
    type: "framework",
    typeLabel: "Framework",
    title: "Priorização de Integrações",
    teaser: "Um critério para decidir qual integração construir primeiro.",
    description:
      "Framework para priorizar integrações entre ferramentas com base no volume de trabalho manual que cada uma elimina.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "novidades-plataformas-ferramentas",
    category: "tecnologia",
    categoryLabel: "Tecnologia",
    type: "analise",
    typeLabel: "Análise de posts",
    title: "Novidades em Plataformas e Ferramentas",
    teaser: "Um resumo do que está sendo lançado e comentado em plataformas de tecnologia.",
    description:
      "Uma análise de posts sobre lançamentos recentes de plataformas e ferramentas de tecnologia para negócios, com o que parece relevante de fato.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },

  // ============ GESTÃO (equipe e gestão empresarial) ============
  {
    id: "estrutura-organizacional-crescimento",
    category: "gestao",
    categoryLabel: "Gestão",
    type: "framework",
    typeLabel: "Framework",
    title: "Estrutura Organizacional para Negócios em Crescimento",
    teaser: "Como desenhar a estrutura do time antes que o crescimento vire bagunça.",
    description:
      "Framework para desenhar a estrutura organizacional em cada fase de crescimento, definindo quando criar um novo cargo, uma nova área ou uma camada de liderança.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "diagnostico-maturidade-gestao",
    category: "gestao",
    categoryLabel: "Gestão",
    type: "ferramenta",
    typeLabel: "Diagnóstico",
    title: "Diagnóstico de Maturidade de Gestão",
    teaser: "Um raio-x de como a liderança do negócio está sendo exercida hoje.",
    description:
      "Questionário guiado que avalia clareza de papéis, cadência de comunicação e qualidade da tomada de decisão na liderança, com um raio-x de prioridades ao final.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "papeis-responsabilidades-raci",
    category: "gestao",
    categoryLabel: "Gestão",
    type: "analise",
    typeLabel: "One-pager",
    title: "Papéis e Responsabilidades sem Sobreposição",
    teaser: "Uma matriz simples para acabar com aquele 'eu pensei que era você'.",
    description:
      "Um one-pager com uma matriz de responsabilidades (quem decide, quem executa, quem é consultado e quem é informado) para eliminar sobreposição e brecha entre funções.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "fluxo-tomada-decisao-impasse",
    category: "gestao",
    categoryLabel: "Gestão",
    type: "framework",
    typeLabel: "Fluxograma",
    title: "Fluxo de Tomada de Decisão em Momentos de Impasse",
    teaser: "Um caminho claro para destravar decisões quando o time não chega a um consenso.",
    description:
      "Fluxograma que organiza como uma decisão travada deve ser destravada: quem escuta os lados, em quanto tempo, e quem tem a palavra final quando não há consenso.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "playbook-gestao-desempenho",
    category: "gestao",
    categoryLabel: "Gestão",
    type: "framework",
    typeLabel: "Playbook",
    title: "Playbook de Gestão de Desempenho",
    teaser: "Um roteiro para avaliar desempenho sem virar burocracia nem virar bagunça.",
    description:
      "Playbook de gestão de desempenho com cadência de avaliação, critérios claros e como transformar uma avaliação em plano de desenvolvimento real.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "estudos-retencao-talentos",
    category: "gestao",
    categoryLabel: "Gestão",
    type: "analise",
    typeLabel: "Compilado de estudos",
    title: "O que os Estudos Dizem sobre Retenção de Talentos",
    teaser: "Um resumo de estudos sobre por que as pessoas realmente ficam ou saem.",
    description:
      "Uma curadoria de estudos sobre retenção de talentos, reunindo os fatores mais citados como determinantes para uma pessoa continuar ou deixar o time.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "lideranca-analise",
    category: "gestao",
    categoryLabel: "Gestão",
    type: "analise",
    typeLabel: "Análise de artigos",
    title: "Liderança em Análise",
    teaser: "Uma leitura organizada sobre o que diferencia uma liderança que o time realmente segue.",
    description:
      "Uma análise de artigos sobre liderança, reunindo os comportamentos mais citados como diferenciais entre líderes que o time segue de verdade e líderes que só ocupam o cargo.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "checklist-reuniao-1-1",
    category: "gestao",
    categoryLabel: "Gestão",
    type: "framework",
    typeLabel: "One-pager",
    title: "Checklist de Reunião 1:1 que Funciona",
    teaser: "O roteiro para o 1:1 deixar de ser só um bate-papo sem rumo.",
    description:
      "Checklist de reunião 1:1 com perguntas e estrutura para que cada conversa individual gere clareza e não só preencha a agenda.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "plano-sucessao-posicoes-chave",
    category: "gestao",
    categoryLabel: "Gestão",
    type: "framework",
    typeLabel: "Framework",
    title: "Plano de Sucessão para Posições-Chave",
    teaser: "Um plano para o negócio não travar se alguém-chave sair amanhã.",
    description:
      "Framework de plano de sucessão para posições-chave, mapeando quem poderia assumir cada função crítica e o que falta preparar em cada sucessor potencial.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "calculadora-turnover-custo",
    category: "gestao",
    categoryLabel: "Gestão",
    type: "ferramenta",
    typeLabel: "Calculadora",
    title: "Calculadora de Turnover e seu Custo Real",
    teaser: "Descubra quanto a rotatividade de time está custando de verdade.",
    description:
      "Calculadora que estima o custo real do turnover, somando desligamento, contratação, treinamento e produtividade perdida até a nova pessoa render.",
    challenges: ["engajar-time", "aumentar-margem"],
    fileUrl: "",
  },
  {
    id: "comunicacao-interna-mudanca",
    category: "gestao",
    categoryLabel: "Gestão",
    type: "framework",
    typeLabel: "Playbook",
    title: "Comunicação Interna em Momentos de Mudança",
    teaser: "Um roteiro para comunicar mudanças sem gerar boato nem pânico.",
    description:
      "Playbook de comunicação interna para momentos de mudança (reestruturação, nova liderança, nova direção), com o que comunicar, quando e por qual canal.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "fluxo-contratacao-perfil-integracao",
    category: "gestao",
    categoryLabel: "Gestão",
    type: "framework",
    typeLabel: "Fluxograma",
    title: "Fluxo de Contratação do Perfil à Integração",
    teaser: "Visualize todo o processo de contratação em uma única imagem.",
    description:
      "Fluxograma que mapeia o processo de contratação completo, da definição do perfil à integração da pessoa contratada, com os pontos de decisão em cada etapa.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "sinais-estrutura-gestao-mudar",
    category: "gestao",
    categoryLabel: "Gestão",
    type: "analise",
    typeLabel: "One-pager",
    title: "Sinais de que a Estrutura de Gestão Precisa Mudar",
    teaser: "Os sinais de que o jeito de gerir o time não acompanhou o crescimento do negócio.",
    description:
      "Um one-pager com os sinais mais comuns de que a estrutura de gestão atual não acompanha mais o tamanho ou a complexidade do negócio.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "pesquisas-feedback-continuo",
    category: "gestao",
    categoryLabel: "Gestão",
    type: "analise",
    typeLabel: "Compilado de pesquisas",
    title: "O que as Pesquisas Dizem sobre Feedback Contínuo",
    teaser: "Uma síntese de pesquisas sobre por que feedback contínuo supera a avaliação anual.",
    description:
      "Uma curadoria de pesquisas sobre feedback contínuo, mostrando por que ciclos mais curtos de feedback tendem a gerar mais mudança de comportamento do que avaliações anuais.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "cadencia-reunioes-lideranca",
    category: "gestao",
    categoryLabel: "Gestão",
    type: "framework",
    typeLabel: "Framework",
    title: "Cadência de Reuniões de Liderança",
    teaser: "Um ritmo de reuniões de liderança que informa decisão em vez de só ocupar agenda.",
    description:
      "Framework de cadência de reuniões de liderança (semanal, mensal, trimestral), com o objetivo específico e a pauta padrão de cada uma.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "gestao-distancia-analise",
    category: "gestao",
    categoryLabel: "Gestão",
    type: "analise",
    typeLabel: "Análise de posts",
    title: "Gestão à Distância em Análise",
    teaser: "Uma leitura do que se fala sobre gerir time remoto ou híbrido sem perder controle.",
    description:
      "Uma análise de posts sobre gestão de times remotos e híbridos, reunindo práticas mais citadas para manter alinhamento sem microgerenciar.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },

  // ============ OPERAÇÕES ============
  {
    id: "estrutura-time-growth",
    category: "operacoes",
    categoryLabel: "Operações",
    type: "framework",
    typeLabel: "Framework",
    title: "Estrutura de Time de Growth",
    teaser: "Como organizar papéis e responsabilidades em um time de growth enxuto.",
    description:
      "Framework para desenhar um time de growth enxuto em negócios de qualquer porte: papéis mínimos, divisão entre aquisição/conversão/retenção e como orquestrar agências e freelancers no mesmo funil.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "planilha-capacidade-operacional",
    category: "operacoes",
    categoryLabel: "Operações",
    type: "ferramenta",
    typeLabel: "Planilha",
    title: "Planilha de Capacidade Operacional por Oferta",
    teaser: "Simule quantas ofertas sua operação atual consegue sustentar sem perder qualidade.",
    description:
      "Planilha para simular a capacidade operacional do time em relação ao número de ofertas, clientes ativos e projetos simultâneos, evitando crescimento de vendas maior do que a operação aguenta.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "papeis-minimos-time-growth",
    category: "operacoes",
    categoryLabel: "Operações",
    type: "analise",
    typeLabel: "One-pager",
    title: "Papéis Mínimos de um Time de Growth Enxuto",
    teaser: "Os papéis essenciais para um time de growth funcionar sem inchar.",
    description:
      "Um one-pager com os papéis mínimos de um time de growth enxuto, e o que cada papel realmente precisa cobrir antes de contratar mais gente.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "fluxo-abertura-nova-operacao",
    category: "operacoes",
    categoryLabel: "Operações",
    type: "framework",
    typeLabel: "Fluxograma",
    title: "Fluxo de Abertura de Nova Operação",
    teaser: "O passo a passo para abrir uma nova frente sem esquecer nada crítico.",
    description:
      "Fluxograma com as etapas de abertura de uma nova operação, unidade ou linha de negócio, dos requisitos legais ao primeiro dia funcionando.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "gestao-fornecedores-freelancers",
    category: "operacoes",
    categoryLabel: "Operações",
    type: "framework",
    typeLabel: "Playbook",
    title: "Gestão de Fornecedores e Freelancers",
    teaser: "Um roteiro para trabalhar com fornecedores e freelancers sem dor de cabeça.",
    description:
      "Playbook de gestão de fornecedores e freelancers, com critérios de seleção, acompanhamento de entregas e avaliação de continuidade.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "estudos-produtividade-times-remotos",
    category: "operacoes",
    categoryLabel: "Operações",
    type: "analise",
    typeLabel: "Compilado de estudos",
    title: "O que os Estudos Dizem sobre Produtividade de Times Remotos",
    teaser: "Um resumo de estudos sobre o que realmente afeta a produtividade remota.",
    description:
      "Uma curadoria de estudos sobre produtividade de times remotos, reunindo os fatores mais citados como determinantes de alta e baixa performance.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "gestao-times-comerciais-analise",
    category: "operacoes",
    categoryLabel: "Operações",
    type: "analise",
    typeLabel: "Análise de artigos",
    title: "Gestão de Times Comerciais em Análise",
    teaser: "Uma leitura organizada sobre o que diferencia uma boa gestão comercial.",
    description:
      "Uma análise de artigos sobre gestão de times comerciais, reunindo práticas de liderança mais citadas por quem escreve sobre o tema.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "checklist-rotina-operacional-semanal",
    category: "operacoes",
    categoryLabel: "Operações",
    type: "framework",
    typeLabel: "One-pager",
    title: "Checklist de Rotina Operacional Semanal",
    teaser: "O mínimo que uma operação saudável revisa toda semana.",
    description:
      "Checklist de rotina operacional semanal com os pontos que evitam que pequenos problemas virem grandes surpresas no fim do mês.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "definicao-slas-entre-areas",
    category: "operacoes",
    categoryLabel: "Operações",
    type: "framework",
    typeLabel: "Framework",
    title: "Definição de SLAs entre Áreas",
    teaser: "Combine prazos entre áreas antes que a falta de combinado vire conflito.",
    description:
      "Framework para definir SLAs entre áreas (por exemplo, marketing e vendas), formalizando prazos e critérios de entrega que hoje talvez só existam de forma implícita.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "calculadora-dimensionamento-equipe",
    category: "operacoes",
    categoryLabel: "Operações",
    type: "ferramenta",
    typeLabel: "Calculadora",
    title: "Calculadora de Dimensionamento de Equipe por Volume de Vendas",
    teaser: "Descubra quantas pessoas sua operação realmente precisa.",
    description:
      "Calculadora que estima o dimensionamento de equipe necessário com base no volume de vendas e na capacidade de atendimento por pessoa.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "onboarding-novos-colaboradores",
    category: "operacoes",
    categoryLabel: "Operações",
    type: "framework",
    typeLabel: "Playbook",
    title: "Onboarding de Novos Colaboradores",
    teaser: "Um roteiro para o colaborador novo produzir mais rápido, com menos atrito.",
    description:
      "Playbook de onboarding com o conteúdo e o cronograma das primeiras semanas de um novo colaborador, reduzindo o tempo até a primeira entrega relevante.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "fluxo-escalonamento-problemas-operacionais",
    category: "operacoes",
    categoryLabel: "Operações",
    type: "framework",
    typeLabel: "Fluxograma",
    title: "Fluxo de Escalonamento de Problemas Operacionais",
    teaser: "Saiba exatamente para quem escalar cada tipo de problema.",
    description:
      "Fluxograma de escalonamento que define para quem cada tipo de problema operacional deve subir, e em quanto tempo, evitando decisões travadas.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
  {
    id: "reunioes-time-growth-deveria-ter",
    category: "operacoes",
    categoryLabel: "Operações",
    type: "analise",
    typeLabel: "One-pager",
    title: "Reuniões que Todo Time de Growth Deveria Ter",
    teaser: "As reuniões que realmente movem o ponteiro, e as que só ocupam agenda.",
    description:
      "Um one-pager com as reuniões essenciais de um time de growth, sua cadência ideal e o objetivo específico de cada uma.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "pesquisas-cultura-alta-performance",
    category: "operacoes",
    categoryLabel: "Operações",
    type: "analise",
    typeLabel: "Compilado de pesquisas",
    title: "O que as Pesquisas Dizem sobre Cultura de Alta Performance",
    teaser: "Uma síntese de pesquisas sobre o que sustenta times de alta performance.",
    description:
      "Uma curadoria de pesquisas sobre cultura de alta performance, reunindo os fatores mais citados como diferenciais de times consistentemente acima da média.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "metas-okrs-growth",
    category: "operacoes",
    categoryLabel: "Operações",
    type: "framework",
    typeLabel: "Framework",
    title: "Metas e OKRs para Growth",
    teaser: "Um jeito de definir metas de growth que o time realmente usa no dia a dia.",
    description:
      "Framework de metas e OKRs voltado para times de growth, com exemplos de objetivos e resultados-chave que conectam atividade a receita.",
    challenges: ["engajar-time"],
    fileUrl: "",
  },
  {
    id: "gestao-operacoes-escala-analise",
    category: "operacoes",
    categoryLabel: "Operações",
    type: "analise",
    typeLabel: "Análise de posts",
    title: "Gestão de Operações em Escala em Análise",
    teaser: "Uma leitura do que se fala sobre operar em escala sem perder qualidade.",
    description:
      "Uma análise de posts sobre gestão de operações em escala, reunindo os desafios mais citados por quem já passou por esse crescimento.",
    challenges: ["melhorar-processos"],
    fileUrl: "",
  },
];

const CATEGORIES = [
  { id: "todos", label: "Todos" },
  { id: "financas", label: "Finanças" },
  { id: "marketing", label: "Marketing" },
  { id: "vendas", label: "Vendas" },
  { id: "ia", label: "IA" },
  { id: "produto", label: "Produto" },
  { id: "tecnologia", label: "Tecnologia" },
  { id: "gestao", label: "Gestão" },
  { id: "operacoes", label: "Operações" },
];

const CHALLENGES = [
  { id: "todos", label: "Todos" },
  { id: "otimizar-marca", label: "Otimizar marca" },
  { id: "gerar-demanda", label: "Gerar demanda" },
  { id: "aumentar-conversao", label: "Aumentar conversão" },
  { id: "melhorar-processos", label: "Melhorar processos" },
  { id: "aumentar-margem", label: "Aumentar margem" },
  { id: "engajar-time", label: "Engajar time" },
];
